name: Send HTTP GET Request

on:
  push:
    branches:
      - main  # main 브랜치에 커밋
  schedule:
    - cron: '*/5 * * * *'  # 5분마다

jobs:
  send-request:
    runs-on: ubuntu-latest
    steps:
    - name: Send HTTP GET request
      run: |
        curl -v -G GET "https://weldaai.com/searchBot/" \
        --data-urlencode "query=" \
        -H "x-api-key: ${{ secrets.x_api_key }}"
